version: 2

jobs:
  download:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get -y update
            sudo apt-get -y install pandoc

      - run:
          name: Download MWS doc
          command: wget -rnH -A html -P src http://docs.developer.amazonservices.com/en_FR/dev_guide/index.html || true

      - run:
          name: Generate markdown version
          command: |
            find src -name "*.html" | while read input
            do
              output=$(echo "${input%.*}.md" | sed s/^src/doc/)
              mkdir -p $(dirname "$output")
              pandoc -f html -t gfm "$input" -o "$output"
              sed -i '/http[s]:\/\/.*\.html/! s/\.html/\.md/g' "$output"
            done

      - run:
          name: Configure git
          command: |
            git config user.email "dev@bizon.solutions"
            git config user.name "Bizon Bot"

      - run:
          name: Add changes
          command: git add src doc

      - run:
          name: Commit changes
          command: git commit -m 'Update MWS documentation' || true

      - run:
          name: Push changes
          command: git push origin master

workflows:
  version: 2
  push:
    jobs:
      - download

  daily:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
             branches:
               only:
                 - master
    jobs:
      - download
