version: 2

jobs:
  download:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get -y update
            sudo apt-get -y install pandoc

      - run:
          name: Download MWS doc
          command: ./scripts/1-download.sh

      - run:
          name: Generate markdown version
          command: ./scripts/2-generate-markdown.sh

      - run:
          name: Configure, commit and push
          command: ./scripts/3-publish.sh

workflows:
  version: 2
  push:
    jobs:
      - download

  daily:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
             branches:
               only:
                 - master
    jobs:
      - download
